#!/bin/bash
export IFS=$'\n'
CMDNAME=`basename $0`
FILENAME_QUEUE="queue_bc.txt"

usage_exit() {
        echo "Usage: ${CMDNAME} [-q queue_filename]" 1>&2
        exit 1
}

mark_finished(){
        sed -i -e "s|${1}|#${1}|g" ${2}
}

BC_BASEDIR=`pwd`
BC_TEMPLATE="%{label}/%{artist} - %{album} - %{date}/%{track} - %{artist} - %{title}"

source ~/.config/dl_bc/config

mkdir -p ${BC_BASEDIR}

while getopts q:h OPT
do
    case $OPT in
        q)  FILENAME_QUEUE=$OPTARG
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done
shift $(($OPTIND - 1))

echo "reading from "${FILENAME_QUEUE}"..."

for LINE in `cat ${FILENAME_QUEUE} | grep -v "^#"`
do
	yes | bandcamp-dl -d -o -r -g -e -k --base-dir=${BC_BASEDIR} --template=$BC_TEMPLATE "${LINE}" || continue
	mark_finished "${LINE}" "${FILENAME_QUEUE}"
done
