#!/bin/bash

## https://qiita.com/hit/items/e95298f689a1ee70ae4a
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`
if [ ${_pcnt} -gt 1 ]; then
        echo "This script has been running now. proc : ${_pcnt}"
  exit 1
fi

if ! command -v scdl 2>&1 >/dev/null
then
        echo "not installed scdl : go https://github.com/scdl-org/scdl . "
        exit 1
fi

export IFS=$'\n'
CMDNAME=`basename $0`
FILENAME_QUEUE="queue_sc.txt"

usage_exit() {
        echo "Usage: ${CMDNAME} [-q queue_filename]" 1>&2
        exit 1
}

mark_finished(){
        sed -i -e "s|${1}|#${1}|g" ${2}
}


DL_BASEDIR=`pwd`
source ~/.config/dl_sc/config
mkdir -p ${DL_BASEDIR}
cd ${DL_BASEDIR}

while getopts q:h OPT
do
    case $OPT in
        q)  FILENAME_QUEUE=$OPTARG
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done
shift $(($OPTIND - 1))

echo "reading from "${FILENAME_QUEUE}"..."

for LINE in `cat ${FILENAME_QUEUE} | grep -v "^#"`
do
	scdl -l ${LINE} || continue
	mark_finished "${LINE}" "${FILENAME_QUEUE}"
done
