#!/bin/bash
export IFS=$'\n'
CMDNAME=`basename $0`
FILENAME_QUEUE="queue_freyr.txt"

usage_exit() {
        echo "Usage: ${CMDNAME} [-q queue_filename]" 1>&2
        exit 1
}

mark_finished(){
        sed -i -e "s|${1}|#${1}|g" ${2}
}

BASEDIR=`pwd`

source ~/.config/dl_freyr/config

mkdir -p ${BASEDIR}

while getopts q:h OPT
do
    case $OPT in
        q)  FILENAME_QUEUE=$OPTARG
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done
shift $(($OPTIND - 1))

cd ${BASEDIR}
echo "reading from "${FILENAME_QUEUE}" ..."

for LINE in `cat ${FILENAME_QUEUE} | grep -v "^#"`
do
	freyr "${LINE}" || continue
	mark_finished "${LINE}" "${FILENAME_QUEUE}"
done
