#!/bin/bash
export IFS=$'\n'
CMDNAME=`basename $0`
FILENAME_QUEUE="queue_ytmdl.txt"

usage_exit() {
	echo "Usage: ${CMDNAME} [-q queue_filename]" 1>&2
	exit 1
}

mark_finished(){
	sed -i -e "s|${1}|#${1}|g" ${2}
}

DL_BASEDIR=`pwd`
USE_COOKIEFILE=false
COOKIEFILE=
source ~/.config/dl_ytmdl/config
mkdir -p ${DL_BASEDIR}
cd ${DL_BASEDIR}

while getopts q:h OPT
do
case $OPT in
q)  FILENAME_QUEUE=$OPTARG
;;
h)  usage_exit
;;
\?) usage_exit
;;
esac
	done
shift $(($OPTIND - 1))

echo "reading from "${FILENAME_QUEUE}"..."

for URL in `cat ${FILENAME_QUEUE} | grep -v "^#"`
do

	echo ${URL}

	if [ ${#URL} -lt 7 ] ; then
		continue
	fi
	if [[ "$URL" == *"youtube"* ]]; then
		SLEEP_REQUESTS=$((RANDOM % 10 + 1))
                MIN_SLEEP_INTERNAL=$((RANDOM % 30 + 30))
                MAX_SLEEP_INTERNAL=$((MIN_SLEEP_INTERNAL + 30))
		yt-dlp -x --audio-format mp3 --embed-thumbnail --sleep-requests ${SLEEP_REQUESTS} --min-sleep-interval ${MIN_SLEEP_INTERNAL=$} --max-sleep-interval ${MAX_SLEEP_INTERNAL} ${URL} || continue	
	else
		yt-dlp -x --audio-format mp3 --embed-thumbnail ${URL} || continue	
	fi
	mark_finished "${URL}" "${FILENAME_QUEUE}"
done
