#!/bin/bash
export IFS=$'\n'
CMDNAME=`basename $0`
FILENAME_QUEUE="queue_youtube.txt"

usage_exit() {
        echo "Usage: ${CMDNAME} [-q queue_filename]" 1>&2
        exit 1
}

mark_finished(){
        sed -i -e "s|${1}|#${1}|g" ${2}
}

if ! command -v yt-dlp 2>&1 >/dev/null
then
	echo "not installed yt-dlp ."
	exit 1
fi

DL_BASEDIR=`pwd`
USE_COOKIEFILE=false
COOKIEFILE=
FILENAME_FORMAT="%(title).150B %(id)s.%(ext)s"
source ~/.config/dl_youtube/config
mkdir -p ${DL_BASEDIR}
cd ${DL_BASEDIR}

while getopts q:h OPT
do
    case $OPT in
        q)  FILENAME_QUEUE=$OPTARG
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done
shift $(($OPTIND - 1))

echo "reading from "${FILENAME_QUEUE}"..."

for LINE in `cat ${FILENAME_QUEUE} | grep -v "^#"`
do

        TITLE=`echo ${LINE} | cut -f 1`
	URL=`echo ${LINE} | cut -f 2`

	if [ ${TITLE} = ${URL} ] ; then 
		TITLE=''
	fi


	echo ${TITLE}
	echo ${URL}

        if [ ${#URL} -lt 7 ] ; then
                continue
        fi

        if [[ "$string" == *"youtube"* ]]; then
        	if "${USE_COOKIEFILE}"; then
                        # yt-dlp --cookies ${COOKIEFILE} --list-formats --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) ${URL} || continue
                        # yt-dlp --cookies ${COOKIEFILE} --list-subs --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) ${URL} || continue
                        if [ ${#TITLE} = 0 ] ; then
                                yt-dlp --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) --cookies ${COOKIEFILE} --encoding utf-8 --all-subs -o ${FILENAME_FORMAT} ${URL} || continue
                        else
                                yt-dlp --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) --cookies ${COOKIEFILE} --encoding utf-8 --all-subs ${URL} -o ${TITLE}.mp4 || continue
                        fi
	        else
        	        # yt-dlp --list-formats --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) ${URL} || continue
        	        # yt-dlp --list-subs --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) ${URL} || continue
		        if [ ${#TITLE} = 0 ] ; then
			        yt-dlp --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) --encoding utf-8 --all-subs -o ${FILENAME_FORMAT} ${URL} || continue
		        else
			        yt-dlp --sleep-requests $((RANDOM % 10 + 1))  --min-sleep-interval $((RANDOM % 30 + 30))  --max-sleep-interval $((RANDOM % 60 + 30)) --encoding utf-8 --all-subs ${URL} -o ${TITLE}.mp4 || continue
		        fi
	        fi
        else
        	if "${USE_COOKIEFILE}"; then
                        # yt-dlp --cookies ${COOKIEFILE} --list-formats ${URL} || continue
                        # yt-dlp --cookies ${COOKIEFILE} --list-subs ${URL} || continue
                        if [ ${#TITLE} = 0 ] ; then
                                yt-dlp --cookies ${COOKIEFILE} --encoding utf-8 --all-subs -o ${FILENAME_FORMAT} ${URL} || continue
                        else
                                yt-dlp --cookies ${COOKIEFILE} --encoding utf-8 --all-subs ${URL} -o ${TITLE}.mp4 || continue
                        fi
	        else
        	        # yt-dlp --list-formats ${URL} || continue
        	        # yt-dlp --list-subs || continue
		        if [ ${#TITLE} = 0 ] ; then
			        yt-dlp --encoding utf-8 --all-subs -o ${FILENAME_FORMAT} ${URL} || continue
		        else
			        yt-dlp --encoding utf-8 --all-subs ${URL} -o ${TITLE}.mp4 || continue
		        fi
	        fi
        fi

        mark_finished "${LINE}" "${FILENAME_QUEUE}"
done
